# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gameController
  pod 'Starscream', '3.0.6'

end
